{
 "title": "Confluent Open Source",
 "tags": [ "5.2.3" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(cp_zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Online",
     "type": "singlestat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(cp_kafka_server_replicamanager_leadercount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "singlestat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_kafka_server_replicamanager_partitioncount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "singlestat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_kafkacontroller_offlinepartitionscount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-kafka.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec{release=~\"$Release\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec{release=~\"$Release\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec{release=~\"$Release\"})",
       "legendFormat": "{{Messages In Per Second}}"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec{release=~\"$Release\"})",
       "legendFormat": "Total Produce Request Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec{release=~\"$Release\"})",
       "legendFormat": "Failed Produce Request Rate"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec{release=~\"$Release\"})",
       "legendFormat": "Fetch Request Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec{release=~\"$Release\"})",
       "legendFormat": "Failed Fetch Request Rate"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent{release=~\"$Release\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_kafkarequesthandlerpool_requesthandleravgidlepercent{release=~\"$Release\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_count{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "singlestat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_success_total{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_count{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "singlestat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_success_total{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_io_ratio{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_incoming_byte_rate{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_network_io_rate{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka REST servers",
     "type": "singlestat",
     "description": "Number of Kafka REST servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(cp_kafka_rest_jetty_metrics_connections_active{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_active{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_opened_rate{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_closed_rate{release=~\"$Release\"}"
      }
     ]
    }
   ]
  },
  { "title": "Confluent KSQL Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "KSQL Metrics: Bytes Consumed",
   "type": "graph",
   "description": "Total number of bytes consumed.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_bytes_consumed_total{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Consumed",
   "type": "graph",
   "description": "Messages consumed per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_messages_consumed_per_sec{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Produced",
   "type": "graph",
   "description": "Messages produced per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_messages_produced_per_sec{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Active Queries",
   "type": "graph",
   "description": "Number of active queries.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_num_active_queries{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Idle Queries",
   "type": "graph",
   "description": "Number of idle queries.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_num_idle_queries{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Persistent Queries",
   "type": "graph",
   "description": "Number of persistent queries.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_ksql_server_metrics_num_persistent_queries{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "singlestat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(cp_kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_opened_rate{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_closed_rate{release=~\"$Release\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "singlestat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(cp_zookeeper_quorumsize{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "singlestat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_zookeeper_numaliveconnections{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_outstandingrequests{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "singlestat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-zookeeper.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_minrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_avgrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_maxrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}